"""Protocol interfaces for dependency inversion.

These structural-typing protocols define the contracts between layers.
Any concrete class that implements the required methods satisfies the
protocol — no inheritance required.
"""

from __future__ import annotations

from collections.abc import AsyncIterator, Callable, Iterable
from typing import Any, Protocol

from data_engineering_copilot.domain.models import (
    DocumentChunk,
    IngestionEvent,
    LLMUsage,
    ParsedDocument,
    RawDocument,
    RetrievedChunk,
)


class CrawlerProtocol(Protocol):
    async def crawl(
        self,
        source: Any,
        max_pages: int,
        on_event: Callable[[IngestionEvent], None] | None = ...,
    ) -> AsyncIterator[RawDocument]: ...


class ParserProtocol(Protocol):
    def parse(self, raw: RawDocument) -> ParsedDocument | None: ...


class ChunkerProtocol(Protocol):
    async def chunk(
        self, document: ParsedDocument, precomputed_embeddings: list[list[float]] | None = None
    ) -> list[DocumentChunk]: ...
    def extract_sentences(self, text: str) -> list[str] | None: ...


class EmbedderProtocol(Protocol):
    async def embed_texts(self, texts: list[str]) -> list[list[float]]: ...
    async def embed_query(self, text: str) -> list[float]: ...
    async def close(self) -> None: ...


class VectorStoreProtocol(Protocol):
    async def upsert_chunks(self, chunks: Iterable[DocumentChunk], vectors: Iterable[list[float]]) -> None: ...
    async def query(
        self,
        query_embedding: list[float],
        top_k: int,
        query_text: str | None = ...,
        source_filter: list[str] | None = ...,
        chunk_type_filter: str | None = ...,
    ) -> list[RetrievedChunk]: ...
    async def count(self) -> int: ...
    async def count_urls(self, source_name: str) -> int: ...
    async def get_content_hash_for_url(self, url: str) -> str | None: ...
    async def delete_by_url(self, url: str) -> None: ...
    def fit_bm25(self, texts: list[str]) -> None: ...
    async def initialize(self) -> None: ...
    async def close(self) -> None: ...


class RedisPipelineProtocol(Protocol):
    def hget(self, name: str | bytes, key: str | bytes) -> RedisPipelineProtocol: ...
    def hset(self, name: str | bytes, key: str | bytes, value: str | bytes) -> RedisPipelineProtocol: ...
    def expire(self, name: str | bytes, time: int) -> RedisPipelineProtocol: ...
    async def execute(self) -> list[bytes | str | None]: ...


class SyncRedisProtocol(Protocol):
    """Minimal protocol for Redis clients used in async contexts."""

    async def hget(self, name: str | bytes, key: str | bytes) -> bytes | str | None: ...
    async def hset(self, name: str | bytes, key: str | bytes, value: str | bytes) -> None: ...
    async def delete(self, *names: str | bytes) -> int: ...
    async def expire(self, name: str | bytes, time: int) -> bool: ...
    def pipeline(self, transaction: bool = ...) -> RedisPipelineProtocol: ...
    async def close(self) -> None: ...


class LLMClientProtocol(Protocol):
    async def generate(self, prompt: str) -> str: ...

    def generate_stream(self, prompt: str) -> AsyncIterator[str]: ...

    @property
    def last_usage(self) -> LLMUsage: ...


class RerankerProtocol(Protocol):
    async def rerank(self, query: str, chunks: list[RetrievedChunk], top_k: int) -> list[RetrievedChunk]: ...
    def diversify_by_lexical_content(self, chunks: list[RetrievedChunk], top_k: int = 5) -> list[RetrievedChunk]: ...
    def is_available(self) -> bool: ...
    async def initialize(self) -> None: ...
    async def close(self) -> None: ...


class TelemetryTracerProtocol(Protocol):
    def start_observation(
        self,
        name: str,
        input: Any = ...,
        as_type: str = ...,
        model: str | None = ...,
    ) -> Any: ...
    def score(self, trace_id: str, name: str, value: float, data_type: str = ..., **kwargs: Any) -> None: ...
    def flush(self) -> None: ...
    async def flush_async(self, timeout: float = ...) -> None: ...
